/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;

import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class registrar_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form registrar_cliente
     */
    public registrar_cliente() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ci = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        pat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ci1 = new javax.swing.JTextField();
        nom1 = new javax.swing.JTextField();
        pat1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("registro cliente");

        ci.setText("N° ci");

        nom.setText("nombre");

        pat.setText("apellido");

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ci1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ci)
                            .addComponent(nom)
                            .addComponent(pat))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ci1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(nom1)
                            .addComponent(pat1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)
                        .addGap(104, 104, 104)
                        .addComponent(jButton2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ci)
                    .addComponent(ci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pat)
                    .addComponent(pat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ci1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ci1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement  stmt = null; 
      ResultSet rs = null;
      PreparedStatement pstmt = null;
      conectar conexion = new conectar();
      
      String nom = nom1.getText();
      String pat = pat1.getText();
      int ci = Integer.parseInt(ci1.getText());
      
      if(nom.isEmpty())//llama al metodo isEmpty
       {
          JOptionPane.showMessageDialog(null, "No se ingreso el nombre!", "Advertencia", JOptionPane.WARNING_MESSAGE);
          return;
       }
      
     try 
      { 
          stmt = conexion.optenerConexion().createStatement();
          //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")"); 
          stmt.executeUpdate("INSERT INTO cliente(ci_cliente,nombre,apellidos) VALUES ("+ci+",'"+nom.toUpperCase()+"','"+pat.toUpperCase()+"')"); 
          System.out.println("Registro insertado correctamente...!!!!");
          JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
          nom1.setText("");
          pat1.setText("");
          ci1.setText("");
      } 
      catch( SQLException e ) 
      {e.printStackTrace();} 
      finally 
      { 
	  if (conexion != null ) 
	  { 
	    try    
	    {conexion.desconectar();} 
	    catch( Exception e ) 
	    {System.out.println( e.getMessage());} 
          } 
      }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ci;
    private javax.swing.JTextField ci1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JLabel pat;
    private javax.swing.JTextField pat1;
    // End of variables declaration//GEN-END:variables
}
