/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;

import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class registros_encomiendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form registros_encomiendas
     */
    public registros_encomiendas() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desc = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        pre = new javax.swing.JLabel();
        cides = new javax.swing.JLabel();
        pla = new javax.swing.JLabel();
        civen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        desc1 = new javax.swing.JTextField();
        dest1 = new javax.swing.JTextField();
        pre1 = new javax.swing.JTextField();
        cides1 = new javax.swing.JTextField();
        pla1 = new javax.swing.JTextField();
        civen1 = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("registro de encomiendas");

        desc.setText("descripcion");

        dest.setText("destino");

        pre.setText("precio");

        cides.setText("ci destinatario");

        pla.setText("N° placa");

        civen.setText("ci vendedora");

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pre1ActionPerformed(evt);
            }
        });

        pla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pla1ActionPerformed(evt);
            }
        });

        civen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civen1ActionPerformed(evt);
            }
        });

        id.setText("id_encomienda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desc)
                            .addComponent(dest)
                            .addComponent(pre)
                            .addComponent(cides)
                            .addComponent(pla)
                            .addComponent(civen)
                            .addComponent(id))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(desc1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(dest1)
                            .addComponent(pre1)
                            .addComponent(cides1)
                            .addComponent(pla1)
                            .addComponent(civen1)
                            .addComponent(id1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addGap(92, 92, 92)
                        .addComponent(jButton2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(desc)
                                            .addComponent(desc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dest)
                                            .addComponent(dest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pre)
                                            .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(cides))
                                    .addComponent(cides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addComponent(pla))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(civen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(civen)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pre1ActionPerformed

    private void pla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pla1ActionPerformed

    private void civen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civen1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Statement  stmt = null; 
      ResultSet rs = null;
      PreparedStatement pstmt = null;
      conectar conexion = new conectar();
      
      int id=Integer.parseInt(id1.getText());
      String desc=desc1.getText();
      String dest=dest1.getText();
      int pre=Integer.parseInt(pre1.getText());
      int cides=Integer.parseInt(cides1.getText());
      String pla=pla1.getText();
      int civen = Integer.parseInt(civen1.getText());
      
      if(desc.isEmpty())//llama al metodo isEmpty
       {
          JOptionPane.showMessageDialog(null, "No se ingreso la descripcion!", "Advertencia", JOptionPane.WARNING_MESSAGE);
          return;
       }
      
     try 
      { 
          stmt = conexion.optenerConexion().createStatement();
          //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")"); 
          stmt.executeUpdate("INSERT INTO encomienda(id_encomienda,descripcion,destino,precio,ci_destinatario,num_placa,ci_vendedora) VALUES ("+id+",'"+desc+"','"+dest+"',"+pre+","+cides+",'"+pla+"',"+civen+")"); 
          System.out.println("Registro insertado correctamente...!!!!");
          JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
          desc1.setText("");
          dest1.setText("");
          pre1.setText("");
          cides1.setText("");
          pla1.setText("");
          civen1.setText("");
          id1.setText("");
      } 
      catch( SQLException e ) 
      {e.printStackTrace();} 
      finally 
      { 
	  if (conexion != null ) 
	  { 
	    try    
	    {conexion.desconectar();} 
	    catch( Exception e ) 
	    {System.out.println( e.getMessage());} 
          } 
      }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cides;
    private javax.swing.JTextField cides1;
    private javax.swing.JLabel civen;
    private javax.swing.JTextField civen1;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField desc1;
    private javax.swing.JLabel dest;
    private javax.swing.JTextField dest1;
    private javax.swing.JLabel id;
    private javax.swing.JTextField id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel pla;
    private javax.swing.JTextField pla1;
    private javax.swing.JLabel pre;
    private javax.swing.JTextField pre1;
    // End of variables declaration//GEN-END:variables
}
