/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;
import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class registrar_viaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form registrar_viaje
     */
    public registrar_viaje() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        asie1 = new javax.swing.JTextField();
        fech1 = new javax.swing.JTextField();
        asie = new javax.swing.JLabel();
        horof1 = new javax.swing.JTextField();
        fech = new javax.swing.JLabel();
        horsal1 = new javax.swing.JTextField();
        horof = new javax.swing.JLabel();
        pre1 = new javax.swing.JTextField();
        horsal = new javax.swing.JLabel();
        cicli1 = new javax.swing.JTextField();
        pre = new javax.swing.JLabel();
        pla1 = new javax.swing.JTextField();
        cicli = new javax.swing.JLabel();
        pla = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("registrar viaje");

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        asie.setText("N° asiento");

        fech.setText("fecha");

        horof.setText("hora en oficina");

        horsal.setText("hora salida");

        pre.setText("precio");

        cicli.setText("ci cliente");

        pla.setText("num placa");

        id.setText("id viaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asie)
                            .addComponent(fech, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horof)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(horsal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cicli)
                            .addComponent(id))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(asie1)
                            .addComponent(fech1)
                            .addComponent(horof1)
                            .addComponent(horsal1)
                            .addComponent(pre1)
                            .addComponent(cicli1)
                            .addComponent(pla1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(id1))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(asie)
                    .addComponent(asie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fech)
                    .addComponent(fech1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(horof)
                    .addComponent(horof1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(horsal)
                    .addComponent(horsal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pre)
                    .addComponent(pre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cicli)
                    .addComponent(cicli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pla)
                    .addComponent(pla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement  stmt = null;
        ResultSet rs = null;
        PreparedStatement pstmt = null;
        conectar conexion = new conectar();
        int id= Integer.parseInt(id1.getText());
        String asie = asie1.getText();
        String fech = fech1.getText();
        String horof= horof1.getText();
        String horsal = horsal1.getText();
        int pre=Integer.parseInt(pre1.getText());
        int cicli= Integer.parseInt(cicli1.getText());
        String pla=pla1.getText();

        if(asie.isEmpty())//llama al metodo isEmpty
        {
            JOptionPane.showMessageDialog(null, "No se ingreso el numero de asiento!", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try
        {
            stmt = conexion.optenerConexion().createStatement();
            //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")");
            stmt.executeUpdate("INSERT INTO viaje(id_viaje,num_asiento,fecha_viaje,hora_en_oficina,hora_salida,precio,ci_cliente,num_placa) VALUES ("+id+",'"+asie+"','"+fech+"','"+horof+"','"+horsal+"',"+pre+","+cicli+",'"+pla+"')");
            System.out.println("Registro insertado correctamente...!!!!");
            JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            asie1.setText("");
            fech1.setText("");
            horof1.setText("");
            horsal1.setText("");
            pre1.setText("");
            cicli1.setText("");
            pla1.setText("");
            id1.setText("");
        }
        catch( SQLException e )
        {e.printStackTrace();}
        finally
        {
            if (conexion != null )
            {
                try
                {conexion.desconectar();}
                catch( Exception e )
                {System.out.println( e.getMessage());}
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asie;
    private javax.swing.JTextField asie1;
    private javax.swing.JLabel cicli;
    private javax.swing.JTextField cicli1;
    private javax.swing.JLabel fech;
    private javax.swing.JTextField fech1;
    private javax.swing.JLabel horof;
    private javax.swing.JTextField horof1;
    private javax.swing.JLabel horsal;
    private javax.swing.JTextField horsal1;
    private javax.swing.JLabel id;
    private javax.swing.JTextField id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel pla;
    private javax.swing.JTextField pla1;
    private javax.swing.JLabel pre;
    private javax.swing.JTextField pre1;
    // End of variables declaration//GEN-END:variables
}
