/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;

import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class reguistrar_envia extends javax.swing.JInternalFrame {

    /**
     * Creates new form reguistrar_envia
     */
    public reguistrar_envia() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cides = new javax.swing.JLabel();
        nomre = new javax.swing.JLabel();
        apre = new javax.swing.JLabel();
        nomdes = new javax.swing.JLabel();
        apdes = new javax.swing.JLabel();
        civen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cides1 = new javax.swing.JTextField();
        nomre1 = new javax.swing.JTextField();
        apre1 = new javax.swing.JTextField();
        nomdes1 = new javax.swing.JTextField();
        apdes1 = new javax.swing.JTextField();
        civen1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("reguistro de invia");

        cides.setText("ci destinatario");

        nomre.setText("nombre remitente");

        apre.setText("apellido remitente");

        nomdes.setText("nombre destinatario");

        apdes.setText("apellido destinatario");

        civen.setText("ci vendedora");

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cides)
                            .addComponent(nomre)
                            .addComponent(apre)
                            .addComponent(nomdes)
                            .addComponent(apdes)
                            .addComponent(civen))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cides1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(nomre1)
                            .addComponent(apre1)
                            .addComponent(nomdes1)
                            .addComponent(apdes1)
                            .addComponent(civen1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cides)
                    .addComponent(cides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomre)
                    .addComponent(nomre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apre)
                    .addComponent(apre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomdes)
                    .addComponent(nomdes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apdes)
                    .addComponent(apdes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civen)
                    .addComponent(civen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement  stmt = null; 
      ResultSet rs = null;
      PreparedStatement pstmt = null;
      conectar conexion = new conectar();
      
      int cides=Integer.parseInt(cides1.getText());
      String nomre = nomre1.getText();
      String apre = apre1.getText();
      String nomdes=nomdes1.getText();
      String apdes=apdes1.getText();
      int civen =Integer.parseInt(civen1.getText());
      
      if(nomre.isEmpty())//llama al metodo isEmpty
       {
          JOptionPane.showMessageDialog(null, "No se ingreso el nombre!", "Advertencia", JOptionPane.WARNING_MESSAGE);
          return;
       }
      
     try 
      { 
          stmt = conexion.optenerConexion().createStatement();
          //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")"); 
          stmt.executeUpdate("INSERT INTO envia(ci_destinatario,nombre_remitente,apellidos_remitente,nombre_destinatario,apellidos_destinatario,ci_vendedora) VALUES ("+cides+",'"+nomre.toUpperCase()+"','"+apre.toUpperCase()+"','"+nomdes.toUpperCase()+"','"+apdes.toUpperCase()+"',"+civen+")"); 
          System.out.println("Registro insertado correctamente...!!!!");
          JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
          cides1.setText("");
          nomre1.setText("");
          apre1.setText("");
          nomdes1.setText("");
          apdes1.setText("");
          civen1.setText("");
      } 
      catch( SQLException e ) 
      {e.printStackTrace();} 
      finally 
      { 
	  if (conexion != null ) 
	  { 
	    try    
	    {conexion.desconectar();} 
	    catch( Exception e ) 
	    {System.out.println( e.getMessage());} 
          } 
      }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apdes;
    private javax.swing.JTextField apdes1;
    private javax.swing.JLabel apre;
    private javax.swing.JTextField apre1;
    private javax.swing.JLabel cides;
    private javax.swing.JTextField cides1;
    private javax.swing.JLabel civen;
    private javax.swing.JTextField civen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nomdes;
    private javax.swing.JTextField nomdes1;
    private javax.swing.JLabel nomre;
    private javax.swing.JTextField nomre1;
    // End of variables declaration//GEN-END:variables
}
