/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package reportes;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import conexion.conectar;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Usuario
 */
public class reporte_chofer extends javax.swing.JInternalFrame {

    /**
     * Creates new form reporte_bus
     */
    public reporte_chofer() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbuscar = new javax.swing.JTextField();
        n = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        campo1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("reporte chofer");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("nostrat tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("generar pdf");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuscarActionPerformed(evt);
            }
        });

        n.setBackground(new java.awt.Color(102, 102, 255));
        n.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n.setText("buscar por nombre");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("referencia(num_licencia)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("columna");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("nuevo dato");

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(n)
                        .addGap(31, 31, 31)
                        .addComponent(cbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(campo3)
                        .addComponent(campo2)
                        .addComponent(campo1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addGap(54, 54, 54)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n)
                    .addComponent(cbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            conectar conexion = new conectar();
          

            Statement stm = conexion.optenerConexion().createStatement();
            String n = cbuscar.getText();

            String consulta = "SELECT * FROM chofer ";
            ResultSet rst = stm.executeQuery(consulta);
            java.sql.ResultSetMetaData rsMd = rst.getMetaData();

            int numeroColumnas = rsMd.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            for(int x=1; x<=numeroColumnas; x++)
            modelo.addColumn(rsMd.getColumnLabel(x));

            while(rst.next())
            {
                Object [] fila = new Object [numeroColumnas];

                for(int y=0;y<numeroColumnas; y++)
                fila[y] =rst.getObject(y+1);

                modelo.addRow(fila);
            }
        }//Final de try

        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        try
        {
            conectar conexion = new conectar();
            //              DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            //              Connection conexion = DriverManager.getConnection ("jdbc:mysql://localhost/unsxx","root","123");

            //DriverManager.registerDriver(new org.postgresql.Driver());
            //Connection conexion = DriverManager.getConnection ("jdbc:postgresql://localhost/unsxx","postgres","123");

            //String url = "jdbc:oracle:thin:@localhost:1521:xe";
            //Connection conn = DriverManager.getConnection(url, "congreso", "nelson");

            Statement stm = conexion.optenerConexion().createStatement();
            String n = cbuscar.getText();

            String consulta = "SELECT * FROM chofer WHERE nombre= " + "'"+n+"'";
            ResultSet rst = stm.executeQuery(consulta);
            java.sql.ResultSetMetaData rsMd = rst.getMetaData();

            int numeroColumnas = rsMd.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            for(int x=1; x<=numeroColumnas; x++)
            modelo.addColumn(rsMd.getColumnLabel(x));

            while(rst.next())
            {
                Object [] fila = new Object [numeroColumnas];

                for(int y=0;y<numeroColumnas; y++)
                fila[y] =rst.getObject(y+1);

                modelo.addRow(fila);
            }
        }//Final de try

        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_nActionPerformed

    private void cbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Document document = new Document();
        try {
            // Ruta de salida del archivo PDF
            String rutaSalida = "d:\\reportes net\\ChoferReporte.pdf"; // Cambiar ruta aquí
            PdfWriter.getInstance(document, new FileOutputStream(rutaSalida));
            document.open();

            // Título del documento
            Paragraph title = new Paragraph("Reporte de Chofer");
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph(" ")); // Espacio entre título y tabla

            // Usar la conexión existente
            conectar conn = new conectar();  // Instanciar tu clase de conexión
            Connection connection = conn.optenerConexion();  // Obtener la conexión

            // Verificar si la conexión es exitosa
            if (connection != null) {
                Statement statement = connection.createStatement();
                String query = "SELECT * FROM chofer";
                ResultSet resultSet = statement.executeQuery(query);

                // Crear una tabla PDF
                PdfPTable table = new PdfPTable(5); // 3 columnas

                // Encabezados de la tabla
                PdfPCell cell1 = new PdfPCell(new Phrase("num_licencia"));
                PdfPCell cell2 = new PdfPCell(new Phrase("Nombre"));
                PdfPCell cell3 = new PdfPCell(new Phrase("Paterno"));
                PdfPCell cell4 = new PdfPCell(new Phrase("Materno"));
                PdfPCell cell5 = new PdfPCell(new Phrase("telefono"));
                

                table.addCell(cell1);
                table.addCell(cell2);
                table.addCell(cell3);
                table.addCell(cell4);
                table.addCell(cell5);

                // Llenar la tabla con los datos
                while (resultSet.next()) {
                    table.addCell(resultSet.getString("num_licencia"));
                    table.addCell(resultSet.getString("nombre"));
                    table.addCell(resultSet.getString("paterno"));
                    table.addCell(resultSet.getString("materno"));
                    table.addCell(resultSet.getString("num_celular"));
                }
                // Agregar la tabla al documento
                document.add(table);
                document.close();

                // Abrir el PDF generado
                File pdfFile = new File(rutaSalida);
                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(pdfFile);
                } else {
                    System.out.println("El sistema no soporta la apertura de archivos.");
                }

                // Cerrar conexión
                conn.desconectar();
            } else {
                System.out.println("Error al conectar con la base de datos.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       PreparedStatement pstmt = null;
conectar conexion = new conectar();

// Recoger valores de los JTextField
String referencia = campo1.getText(); // Dato de referencia (num_placa)
String columna = campo2.getText();   // Nombre de la columna a modificar
String nuevoDato = campo3.getText(); // Nuevo valor

// Verificar si algún campo está vacío
if (referencia.isEmpty() || columna.isEmpty() || nuevoDato.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Faltan datos por llenar!", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
}

try {
    // Validar que el nombre de la columna sea válido (solo letras y guiones bajos)
    if (!columna.matches("^[a-zA-Z_]+$")) {
        JOptionPane.showMessageDialog(null, "El nombre de la columna contiene caracteres inválidos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Construir la consulta SQL de actualización
    String sql = "UPDATE chofer SET " + columna + " = ? WHERE num_licencia = ?";
    pstmt = conexion.optenerConexion().prepareStatement(sql);

    // Asignar los valores a los parámetros de la consulta
    pstmt.setString(1, nuevoDato);    // Nuevo dato
    pstmt.setString(2, referencia);  // Referencia (num_placa)

    // Ejecutar la actualización
    int rowsAffected = pstmt.executeUpdate();

    // Mostrar mensajes según el resultado
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Dato actualizado correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró el registro con el valor de referencia proporcionado", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // Limpiar los JTextField
    campo1.setText("");
    campo2.setText("");
    campo3.setText("");

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Ocurrió un error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
} finally {
    // Liberar recursos
    try {
        if (pstmt != null) pstmt.close();
        if (conexion != null) conexion.desconectar();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField cbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton n;
    // End of variables declaration//GEN-END:variables
}
