/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package herramientas;
import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class eliminar_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form eliminar_cliente
     */
    public eliminar_cliente() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ci = new javax.swing.JLabel();
        ci1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lic = new javax.swing.JLabel();
        lic1 = new javax.swing.JTextField();
        num1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("eliminar ");

        jButton1.setText("eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ci.setText("ci cliente");

        jLabel1.setText("eliminar cliente");

        jLabel2.setText("eliminar chofer");

        lic.setText("num licencia");

        num1.setText("eliminar");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ci)
                            .addComponent(lic))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ci1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lic1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(num1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ci)
                    .addComponent(ci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lic)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(num1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement stmt = null;
        PreparedStatement pstmt = null;
        conectar conexion = new conectar();

        int ci = Integer.parseInt(ci1.getText());

            if (ci1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ingresó el CI!", "Advertencia", JOptionPane.WARNING_MESSAGE);
           return;
        }

        try {
            stmt = conexion.optenerConexion().createStatement();
                // Eliminar el cliente por su CI
            int rowsAffected = stmt.executeUpdate("DELETE FROM cliente WHERE ci_cliente = " + ci);
    
            if (rowsAffected > 0) {
        System.out.println("Registro eliminado correctamente...!!!!");
        JOptionPane.showMessageDialog(null, "Se eliminó correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró el cliente con el CI especificado", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // Limpiar el campo de texto
    ci1.setText("");
} catch (SQLException e) {
    e.printStackTrace();
} finally {
    if (conexion != null) {
        try {
            conexion.desconectar();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        Statement stmt = null;
        PreparedStatement pstmt = null;
        conectar conexion = new conectar();

        int lic = Integer.parseInt(lic1.getText());

            if (lic1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ingresó el CI!", "Advertencia", JOptionPane.WARNING_MESSAGE);
           return;
        }

        try {
            stmt = conexion.optenerConexion().createStatement();
                // Eliminar el cliente por su CI
            int rowsAffected = stmt.executeUpdate("DELETE FROM chofer WHERE num_licencia = " + lic);
    
            if (rowsAffected > 0) {
        System.out.println("Registro eliminado correctamente...!!!!");
        JOptionPane.showMessageDialog(null, "Se eliminó correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró el cliente con el CI especificado", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // Limpiar el campo de texto
    lic1.setText("");
} catch (SQLException e) {
    e.printStackTrace();
} finally {
    if (conexion != null) {
        try {
            conexion.desconectar();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
    }//GEN-LAST:event_num1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ci;
    private javax.swing.JTextField ci1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lic;
    private javax.swing.JTextField lic1;
    private javax.swing.JButton num1;
    // End of variables declaration//GEN-END:variables
}
