/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;

import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class registrar_vendedora extends javax.swing.JInternalFrame {

    /**
     * Creates new form registrar_vendedora
     */
    public registrar_vendedora() {
        initComponents();
        setLocation(200,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ci1 = new javax.swing.JTextField();
        ci = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        pat = new javax.swing.JLabel();
        pat1 = new javax.swing.JTextField();
        mat = new javax.swing.JLabel();
        mat1 = new javax.swing.JTextField();
        fono = new javax.swing.JLabel();
        fono1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("regintrar vendedora");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        ci1.setBackground(new java.awt.Color(255, 255, 255));
        ci1.setForeground(new java.awt.Color(0, 0, 0));

        ci.setForeground(new java.awt.Color(255, 255, 255));
        ci.setText("N° ci");

        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("nombre");

        nom1.setBackground(new java.awt.Color(255, 255, 255));
        nom1.setForeground(new java.awt.Color(0, 0, 0));

        pat.setForeground(new java.awt.Color(255, 255, 255));
        pat.setText("paterno");

        pat1.setBackground(new java.awt.Color(255, 255, 255));
        pat1.setForeground(new java.awt.Color(0, 0, 0));

        mat.setForeground(new java.awt.Color(255, 255, 255));
        mat.setText("materno");

        mat1.setBackground(new java.awt.Color(255, 255, 255));
        mat1.setForeground(new java.awt.Color(0, 0, 0));

        fono.setForeground(new java.awt.Color(255, 255, 255));
        fono.setText("telefono");

        fono1.setBackground(new java.awt.Color(255, 255, 255));
        fono1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGINTRO VENDEDORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(nom1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ci1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ci, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mat1)
                                .addComponent(fono1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(ci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(fono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement  stmt = null; 
      ResultSet rs = null;
      PreparedStatement pstmt = null;
      conectar conexion = new conectar();
      
      int ci=Integer.parseInt(ci1.getText());
      String nom = nom1.getText();
      String pat = pat1.getText();
      String mat= mat1.getText();
      int fono = Integer.parseInt(fono1.getText());
      
      if(nom.isEmpty())//llama al metodo isEmpty
       {
          JOptionPane.showMessageDialog(null, "No se ingreso el nombre!", "Advertencia", JOptionPane.WARNING_MESSAGE);
          return;
       }
      
     try 
      { 
          stmt = conexion.optenerConexion().createStatement();
          //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")"); 
          stmt.executeUpdate("INSERT INTO vendedora(ci_vendedora,nombre,paterno,materno,mun_celular) VALUES ("+ci+",'"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+mat.toUpperCase()+"',"+fono+")"); 
          System.out.println("Registro insertado correctamente...!!!!");
          JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
          ci1.setText("");
          nom1.setText("");
          pat1.setText("");
          mat1.setText("");
          fono1.setText("");
      } 
      catch( SQLException e ) 
      {e.printStackTrace();} 
      finally 
      { 
	  if (conexion != null ) 
	  { 
	    try    
	    {conexion.desconectar();} 
	    catch( Exception e ) 
	    {System.out.println( e.getMessage());} 
          } 
      }                        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ci;
    private javax.swing.JTextField ci1;
    private javax.swing.JLabel fono;
    private javax.swing.JTextField fono1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mat;
    private javax.swing.JTextField mat1;
    private javax.swing.JLabel nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JLabel pat;
    private javax.swing.JTextField pat1;
    // End of variables declaration//GEN-END:variables
}
