/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package registros;

import conexion.conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import trans_norte_potosi_mysql.principal;

/**
 *
 * @author Usuario
 */
public class reguistrar_envia extends javax.swing.JInternalFrame {
     private javax.swing.JDesktopPane escritorio;

    // Constructor que acepta JDesktopPane como parámetro
    public reguistrar_envia(javax.swing.JDesktopPane escritorio) {
        initComponents();
        this.escritorio = escritorio;
        setLocation(200, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cides = new javax.swing.JLabel();
        cides1 = new javax.swing.JTextField();
        nomre = new javax.swing.JLabel();
        nomre1 = new javax.swing.JTextField();
        apre = new javax.swing.JLabel();
        apre1 = new javax.swing.JTextField();
        nomdes = new javax.swing.JLabel();
        nomdes1 = new javax.swing.JTextField();
        apdes = new javax.swing.JLabel();
        apdes1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        cides.setForeground(new java.awt.Color(255, 255, 255));
        cides.setText("ci destinatario");

        cides1.setBackground(new java.awt.Color(255, 255, 255));
        cides1.setForeground(new java.awt.Color(0, 0, 0));
        cides1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cides1ActionPerformed(evt);
            }
        });

        nomre.setForeground(new java.awt.Color(255, 255, 255));
        nomre.setText("nombre remitente");

        nomre1.setBackground(new java.awt.Color(255, 255, 255));
        nomre1.setForeground(new java.awt.Color(0, 0, 0));

        apre.setForeground(new java.awt.Color(255, 255, 255));
        apre.setText("apellido remitente");

        apre1.setBackground(new java.awt.Color(255, 255, 255));
        apre1.setForeground(new java.awt.Color(0, 0, 0));

        nomdes.setForeground(new java.awt.Color(255, 255, 255));
        nomdes.setText("nombre destinatario");

        nomdes1.setBackground(new java.awt.Color(255, 255, 255));
        nomdes1.setForeground(new java.awt.Color(0, 0, 0));

        apdes.setForeground(new java.awt.Color(255, 255, 255));
        apdes.setText("apellido destinatario");

        apdes1.setBackground(new java.awt.Color(255, 255, 255));
        apdes1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO REMITENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apdes)
                            .addComponent(nomdes)
                            .addComponent(apre)
                            .addComponent(nomre)
                            .addComponent(cides)
                            .addComponent(nomdes1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(apre1)
                            .addComponent(nomre1)
                            .addComponent(cides1)
                            .addComponent(apdes1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(cides)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nomre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(apre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nomdes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomdes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(apdes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apdes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Statement  stmt = null; 
      ResultSet rs = null;
      PreparedStatement pstmt = null;
      conectar conexion = new conectar();
      
      int cides=Integer.parseInt(cides1.getText());
      String nomre = nomre1.getText();
      String apre = apre1.getText();
      String nomdes=nomdes1.getText();
      String apdes=apdes1.getText();
      
      if(nomre.isEmpty())//llama al metodo isEmpty
       {
          JOptionPane.showMessageDialog(null, "No se ingreso el nombre!", "Advertencia", JOptionPane.WARNING_MESSAGE);
          return;
       }
      
     try 
      { 
          stmt = conexion.optenerConexion().createStatement();
          //stmt.executeUpdate("INSERT INTO cliente(nombres,paterno) VALUES ('"+nom.toUpperCase()+"','"+pat.toUpperCase()+"','"+dir.toUpperCase()+"',"+fono+")"); 
          stmt.executeUpdate("INSERT INTO envia(ci_destinatario,nombre_remitente,apellido_remitente,nombre_destinatario,apellido_destinatario) VALUES ("+cides+",'"+nomre.toUpperCase()+"','"+apre.toUpperCase()+"','"+nomdes.toUpperCase()+"','"+apdes.toUpperCase()+"')"); 
          System.out.println("Registro insertado correctamente...!!!!");
          JOptionPane.showMessageDialog(null, "Se inserto correctamente", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
          
          ((principal) escritorio.getTopLevelAncestor()).setCiDestinatario(cides);
          registros_encomiendas viajeForm = new registros_encomiendas(escritorio,cides);
          escritorio.add(viajeForm);
          viajeForm.show();
         
          cides1.setText("");
          nomre1.setText("");
          apre1.setText("");
          nomdes1.setText("");
          apdes1.setText("");
          this.dispose();
      } 
      catch( SQLException e ) 
      {e.printStackTrace();} 
      finally 
      { 
	  if (conexion != null ) 
	  { 
	    try    
	    {conexion.desconectar();} 
	    catch( Exception e ) 
	    {System.out.println( e.getMessage());} 
          } 
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cides1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cides1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cides1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apdes;
    private javax.swing.JTextField apdes1;
    private javax.swing.JLabel apre;
    private javax.swing.JTextField apre1;
    private javax.swing.JLabel cides;
    private javax.swing.JTextField cides1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomdes;
    private javax.swing.JTextField nomdes1;
    private javax.swing.JLabel nomre;
    private javax.swing.JTextField nomre1;
    // End of variables declaration//GEN-END:variables
}
